//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronLoto2v.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IronLoto2v.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 треугольник æртæкъуымон
        ///2 озеро цад
        ///3 рыба кæсаг
        ///4 склеп зæппадз
        ///5 круг тымбыл
        ///6 тополь гæдыбæлас
        ///7 волк бирæгъ
        ///8 кошка гæды
        ///9 медведь арс
        ///10 умножение хаткæнынад
        ///11 творог къæдор
        ///12 тридцать æртын
        ///13 чиж дзылы
        ///14 фрукты дыргътæ
        ///15 восемьдесят цыппарыссæдзы
        ///16 собака куыдз
        ///17 мельница куырой
        ///18 курица карк
        ///19 корзина чыргъæд
        ///20 блин лауыз
        ///21 незабудка дзæнгæрæгой
        ///22 овал дæргъдымбыл
        ///23 девяносто науадз
        ///24 кефир мисын
        ///25 черемша давон
        ///26 редис булкъ
        ///27 гвоздика даричин
        ///28 поле бы [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string dictionary {
            get {
                return ResourceManager.GetString("dictionary", resourceCulture);
            }
        }
    }
}
